### ISSUE TITLE
Using Validar with a sealed class creates CA errors.

### ISSUE THREAD

**Issue by tom-englert** [Fody/Validar#11]
```
[ImplementPropertyChanged, InjectValidation]
public sealed class MyClass : INotifyPropertyChanged
{
```

creates the following static code analysis errors:
```
Microsoft.Design : ''MyClass.IDataErrorInfo.Error.get()'' is a virtual member declared in a sealed type.
Mark the member non-virtual or, if the type should be extensible, unseal it.
```

(same error repeated for all other interfaces members)

**Comment by SimonCropp** [comment]
note that INotifyPropertyChanged is redundant when u have ImplementPropertyChanged

**Comment by SimonCropp** [comment]
did u want to have a go at submitting a PR for this?

**Comment by tom-englert** [comment]
INotifyPropertyChanged is redundant: Yes, I'm aware of this. 
The class where I copied this sample code from just needed to have it declared, because some consumers required this.

**Comment by tom-englert** [comment]
PR: No, I had no time yet to look into the sources, and probably I won't in the near future.
