### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by amarf** [Fody/Validar#14]
If I am use custom attribute and InjectValidationAttribute, i get runtime exception
If I use a custom attribute with an InjectValidationAttribute, an exception occurs at run time, when the following code is executed:
` public ValidationTemplate(T target)`
`{`
`var attributes = target.GetType().GetCustomAttributes(false).ToList();`
`}`
**Exception:**
An exception of type 'System.TypeLoadException' occurred in mscorlib.dll but was not handled in user code
Additional information: Could not load type "Validar.InjectValidationAttribute" from assembly "PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"

**Comment by SimonCropp** [comment]
can u upload a repro
