### ISSUE TITLE
Validations visible when resetting or clearing values in ViewModel - allow reset for validation too.

### ISSUE THREAD

**Issue by sekulicb** [Fody/Validar#190]
Hi. Thanks for the library. One question. When user is done with input on the form, saves the data and then I have to clear, or reset bindings in ViewModel for the next use, validations pops up right from the start on showing form again. I get that this can be expected since now validation is failing, but there should be a way to say - this is clean state, track the input and validate again. I don't see an option to somehow reset or clear validation errors as well, without calling validation template, which beats the purpose of Inject validation if you ask me.

I'm using Validar + FluentValidation nuget package.
Validar : 1.8.0
FluentValidation 8.6.2
WPF application running on top of .NET CORE 3.1

**Comment by SimonCropp** [comment]
glad u like validar. can u please re read the issue template and ensure you have followed all the steps

**Comment by sekulicb** [comment]
Yes, all steps are followed to the letter. The problem that I have is how to reset errors to pre-validation state?

**Comment by SimonCropp** [comment]
this doesn’t seem like a bug. as per the issue template, questions should be asked on stackoverflow https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/config.yml

**Comment by sekulicb** [comment]
In my opinion this might not be a bug but is definitely a place to mark something as improvement or feature request since this should work out of the box, and it doesn't. Taking it to the gitter is not taking particular case seriously but to each its own I guess.

**Comment by SimonCropp** [comment]
happy to consider a pill request if you want to improve it

**Comment by sekulicb** [comment]
Actually now I have a real bug. If I remove InjectValidation template, and provide ValidationTemplate instance my self, like in the example [https://github.com/Fody/Validar/issues/5#issuecomment-43493350](#5), the UI does not get notified.

**Comment by SimonCropp** [comment]
@sekulicb follow the issue template and we can look into it
