### ISSUE TITLE
Couldn't access INotifyDataErrorInfo members on view-model by another method

### ISSUE THREAD

**Issue by yesuraj130** [Fody/Validar#221]
Hi @SimonCropp, First thanks for the library.
Definitely ```[InjectValidation]``` works great, saves time and makes class more readable.

However when I would like to access INotifyDataErrorInfo members on my view-model in another method, its not possible now. because INotifyDataErrorInfo members are implemented at build time by ```[InjectValidation]```.

For Example,

```c#
public class ValidationTemplate : INotifyDataErrorInfo   // General Validation Template
{
     // Implementation of INotifyDataErrorInfo
}

[InjectValidation]
Public class User : INotifyPropertyChanged   // View Model
{
    [MaxLength(20)]
    public string Name{ get; set; }

    internal bool IsError()   // Internal method required
    {
          return HasErrors;    // Error since HasErrors implemented at build time by [InjectValidation]
    }
}
```
This issues may be similar to #5

**Comment by yesuraj130** [comment]
The solution could be,
Allow the class to implement INotifyDataErrorInfo and replace it with implementation provided on validation template at build time

For Example,
```c#
public class ValidationTemplate : INotifyDataErrorInfo   // General Validation Template
{
     // Actual Implementation of INotifyDataErrorInfo
}

[InjectValidation]
Public class User : INotifyPropertyChanged, INotifyDataErrorInfo   // View Model with INotifyDataErrorInfo implemented
{
    [MaxLength(20)]
    public string Name{ get; set; }

    internal bool IsError()   // Internal method required
    {
        return HasErrors;    // No Error now.  since HasErrors implemented
    }

     // Empty implementation will be replaced by ValidationTemplate at build time
     public bool HasErrors => throw new NotImplementedException();
     public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;
     public IEnumerable GetErrors(string propertyName)
     {
        throw new NotImplementedException();
     }
     // end of Empty implementation 
}
```

What do you think @SimonCropp?

**Comment by SimonCropp** [comment]
Did you read the issue template?

**Comment by yesuraj130** [comment]
> Did you read the issue template?

Hi @SimonCropp,

I have read the issue template, now i understood for raising a issue I have to be a patron (but me not).
If this issue not eligible for consideration, Could you please close this issue.

Sorry for the inconvenience, If caused. Thank you.

**Comment by SimonCropp** [comment]
You need to be a patron to be using Fody. Being a patron when raising an issue is a side effect of that. 

If you want to have a go at submitting a PR to fix this, i would consider it
