### ISSUE TITLE
WPF Framework 4.0 validation of complex object

### ISSUE THREAD

**Issue by advapiIT** [Fody/Validar#7]
Hello,
I'm tring to validate a quite simple model under WPF (in real case I use Caliburn Micro as MVVM framework)

My problem is that I can't disable an confirm button if there're error in the  nested model's property

consider this case

    public class MainObjectValidator : AbstractValidator<MainObject>
    {
        public MainObjectValidator()
        {
            RuleFor(x => x.Child).SetValidator(new ChildObjectValidator());
            RuleFor(x => x.Name).NotEmpty();
        }
    }

    [InjectValidation]
    public class ChildObject : INotifyPropertyChanged
    {
        private int age;

        public int Age
        {
            get
            {
                return this.age;
            }
            set
            {
                this.age = value;
                NotifyPropertyChanged("Age");
            }
        }

        private void NotifyPropertyChanged(String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }

    public class ChildObjectValidator : AbstractValidator<ChildObject>
    {
        public ChildObjectValidator()
        {
            RuleFor(x => x.Age).GreaterThan(18);
        }
    }

and Here's my ViewModel

    public class ViewModel : ViewModelBase
    {
        private MainObject dummy;

        public MainObject Dummy
        {
            get
            {
                return this.dummy;
            }
            set
            {
                this.dummy = value;
                OnPropertyChanged(() => Dummy);
            }
        }

        public ViewModel()
        {
            this.Dummy = new MainObject();

            Dummy.Child.Age = 15;
            Dummy.Name = "paolo";

            CreateLoadCommand();
        }

        private void CreateLoadCommand()
        {
            LoadDataCommand = new RelayCommand(this.DoSomething());

        }

        public ICommand LoadDataCommand
        {
            get;
            internal set;
        }

        public bool CanLoadDataCommand
        {
            get
            {
                return false;
            }

        }

        private Action DoSomething()
        {
            return () =>
                {

                    var x = Dummy.GetType().GetField("validationTemplate", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.FlattenHierarchy);

                    var t = (ValidationTemplate)x.GetValue(Dummy);
                };
        }
    }

and my View
```
<code>
Window x:Class="WPFExample.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:telerik="http://schemas.telerik.com/2008/xaml/presentation"
        Title="MainWindow" Height="350" Width="525">
    <Grid DataContext="{Binding}">
        <Grid.RowDefinitions>
            <RowDefinition Height="25"></RowDefinition>
            <RowDefinition Height="25"></RowDefinition>
            <RowDefinition Height="25"></RowDefinition>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition></ColumnDefinition>
            <ColumnDefinition></ColumnDefinition>
        </Grid.ColumnDefinitions>
        
        <Label Content="Name" Grid.Column="0" Grid.Row="0"></Label>
        <Label Content="Age" Grid.Column="0" Grid.Row="1"></Label>
        <TextBox Text="{Binding Dummy.Name, Mode=TwoWay, ValidatesOnDataErrors=True}" Grid.Row="0" Grid.Column="1"></TextBox>

        <telerik:RadMaskedNumericInput Value="{Binding Dummy.Child.Age, Mode=TwoWay, ValidatesOnDataErrors=True}" Grid.Row="1" Grid.Column="1"></telerik:RadMaskedNumericInput>
        <Button Content="Ok" Grid.Row="2" Grid.ColumnSpan="2" Command="{Binding LoadDataCommand}"></Button>
    </Grid>
</Window>
</code>
```
Even if on screen Age field get's red I can't disable the button, if I look at the value of

    var t = (ValidationTemplate)x.GetValue(Dummy);

`t.HasError` it's always true

I've used ValidationTemplate present in your homepage

**Comment by SimonCropp** [comment]
upload a zipped repro somewhere and i will have a look at it

**Comment by GeertvanHorrik** [comment]
This is standard WPF validation stuff, has actually nothing to do with Fody / Validar. Please create a failing unit test to prove that this is something inside Validar itself.

**Comment by SimonCropp** [comment]
feel free to raise a new issue when you have a repro
